// This file is generated by npm run build:icons

export type IconName =
	| "arrow"
	| "comments"
	| "facebook"
	| "github"
	| "linkedin"
	| "share"
	| "tableOfContents"
	| "tiktok"
	| "twitter"
	| "youtube";
